package util

const TGT_PREFIX = "TGT_"
const ST_PREFIX = "ST_"

const SERVICE_TICKET_PREFIX = "SSO_SERVICE_TICKET_PREFIX_"
const SERVICE_TICKET_TIME_TO_LIVE = 7 * 24 * 60 * 60 * 1000

const TICKET_GRANTING_TICKET_PREFIX = "SSO_TICKET_GRANTING_TICKET_"
const TICKET_GRANTING_TICKET_TIME_TO_LIVE = 365 * 24 * 60 * 60 * 1000

const COOKIE_DOMAIN = "yourhost.com"
