package util

const REDIS_CODE_TIMEOUT = 300000
const REDIS_CODE_PREFIX = "OAUTH_CODE_"
//const TOKEN_VALIDATE_TIME_IN_SECONDS = 60 * 60 * 24 * 365
const TOKEN_VALIDATE_TIME_IN_SECONDS = 60
const DEFAULT_TOKEN_TYPE = "bearer"
